routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::post('verificate', 'PhoneVerificationController@index');
Route::post('feedback', 'BaseController@sensFeedback');
Route::post('winners', 'BaseController@getWinners');

Route::group(['prefix' => 'personal'], function () {
	Route::get('/', 'BaseController@personalPage')->name('personal');
	//Route::get('check/add', 'BaseController@indexCheck')->name('user.add.check');
	//Route::post('check/add', 'BaseController@indexCheck');
	Route::get('check/list', 'BaseController@userListCheck')->name('user.list.check');
});

Route::group(['middleware' => 'auth'], function () {
	
	Route::group(['middleware' => ['admin']], function () {
		Route::group(['prefix' => 'admin'], function () {
			Route::get('sendsms', 'BaseController@sendOldSMS')->name('sendsms');
			Route::post('sendsms', 'BaseController@sendOldSMS');
			Route::get('check', 'BaseController@nextCheck')->name('check');
			Route::get('check/{check}/view', 'BaseController@viewCheckFile')->name('admin.view.check');
			Route::get('check/list', 'BaseController@listCheck')->name('check.list');
			Route::get('check/export', 'BaseController@exportCheck')->name('check.export');
			Route::post('check/export', 'BaseController@exportCheck');
			Route::get('check/export/files', 'BaseController@getExports')->name('check.export.files');
			Route::post('check/export/files', 'BaseController@getExports');
			Route::post('check/update/{check}', 'BaseController@updateCheck')->name('check.update');
			Route::get('prizes', 'BaseController@listPrizes')->name('admin.prizes');
			Route::get('prizes/add', 'BaseController@addPrize')->name('admin.prizes.add');
			Route::post('prizes/add', 'BaseController@addPrize');
			Route::get('prizes/{prize}/delete', 'BaseController@deletePrize')->name('admin.prizes.delete');
			Route::get('raffles', 'BaseController@listRaffles')->name('admin.raffles');
			Route::get('raffles/add', 'BaseController@addRaffle')->name('admin.raffles.add');
			Route::post('raffles/add', 'BaseController@addRaffle');
			Route::get('raffles/{raffle}/delete', 'BaseController@deleteRaffle')->name('admin.raffle.delete');
			Route::get('raffles/{raffle}/activate', 'BaseController@activateRaffle')->name('admin.raffle.activate');
			Route::get('raffles/{raffle}/winners', 'BaseController@listRaffleWinners')->name('admin.raffle.winners');
			Route::get('raffles/{raffle}/winners/add', 'BaseController@addRaffleWinners')->name('admin.raffle.winners.add');
			Route::post('raffles/{raffle}/winners/add', 'BaseController@addRaffleWinners');
			Route::get('raffles/{raffle}/winners/{winner}/delete', 'BaseController@deleteWinner')->name('admin.raffle.winners.delete');
		});
	});
});
Route::get('/logout', 'Auth\LoginController@logout');
Auth::routes();

//Route::get('/home', 'BaseController@index')->name('home');

app/Check.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;
use Image;
use Carbon\Carbon;

class Check extends Model
{
    //
    use SoftDeletes;


    protected $fillable = [
        'unp', 'buy_time', 'serial', 'photo', 'reason'
    ];

    protected $dates = ['deleted_at'];
    
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function winners()
    {
        return $this->hasMany('App\Winner'); 
    }

    public function scopeCreateFrom($query, $date)
    {
        if ($date !== NULL && $date != '')
            return $query->where('created_at', '>', Carbon::parse($date));
        return $query;
    }

    public function scopeCreateUntil($query, $date)
    {
        if ($date !== NULL && $date != '')
            return $query->where('created_at', '<=', Carbon::parse($date));
        return $query;
    }

    public function getPhotoAttribute($value)
    {
        if (substr($value, -4) == '.pdf')
            return Storage::url($value);
    	return Image::make(Storage::get($value))->encode('data-url');
    }

    public function getPhotoPathAttribute()
    {
        return Storage::url($this->getOriginal()['photo']);   
    }

    public function getImageAttribute()
    {
        if (substr($this->getOriginal()['photo'], -4) == '.pdf')
            return false;
        return true;
    }

    public function approve($count=1)
    {
        $this->active = true;
        $this->save();
        $raffle = Raffle::where('start', '<=', Carbon::parse($this->created_at))->where('end', '>=', Carbon::parse($this->created_at))->first();
        if (!$raffle)
        {
            return false;
        }
        $this->user->sendRocketSMS($this->smsText($this->id, $raffle->sms_date));
        if ($count > 1)
        {
            for ($i=1; $i<$count; $i++)
            {
                $newCheck = $this->replicate();
                $newCheck->created_at = $this->created_at;
                $newCheck->save();
                $this->user->sendRocketSMS($this->smsText($newCheck->id, $raffle->sms_date));
            }
        }
        //$this->user->sendRocketSMS('Ваш чек номер: '.$this->id.'. Одобрен.');
        return true;
    }

    public function decline($reason)
    {
        $this->reason = $reason;
        $this->save();
        $this->user->sendRocketSMS('Ваш чек №'.$this->id.' отклонен. Причина: '.$reason);
        $this->delete();
        return true;
    }

    private function smsText($id, $name)
    {
        return 'Ваш код участника: '.$id.'. Розыгрыш призов '.$name.'. Играй с BAMBOLINA!';
    }

    public function sendApprovedSms($count)
    {
        $raffle = Raffle::where('start', '<=', Carbon::parse($this->created_at))->where('end', '>=', Carbon::parse($this->created_at))->first();
        if (!$raffle)
        {
            return false;
        }
        if ($count > 0)
        {
            for ($i=1; $i<=$count; $i++)
            {
                $newCheck = $this->replicate();
                $newCheck->created_at = $this->created_at;
                $newCheck->save();
                $this->user->sendRocketSMS($this->smsText($newCheck->id, $raffle->sms_date));
            }
        }

    }

}

resources/views/admin/check.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                @if (!$check)
                <div class="panel-heading">Проверка чека</div>
                <div class="panel-body">
                    Нету чеков для проверки
                </div>
                @else
                <div class="panel-heading">Чек № {{$check->id}}</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('check.update', ['check' => $check]) }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label class="col-md-5 text-right">УНП продавца</label>
                            <div class="col-md-6">{{$check->unp}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-5 text-right">Дата и время в чеке</label>
                            <div class="col-md-6"><span>{{$check->buy_time}}</span></div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-5 text-right">Серийный номер чека</label>
                            <div class="col-md-6">{{$check->serial}}</div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-5 text-right">Фото кассового чека</label>
                            @if ($check->image)
                            <div class="col-md-6"><a href="#" data-toggle="modal" data-target="#PhotoCheck"><img src="{{$check->photo}}" class="img-thumbnail"></a></div>
                            @else
                            <div class="col-md-6"><a href="{{route('admin.view.check', ['check' => $check])}}" target="_blank">PDF</a></div>
                            @endif
                        </div>
                        <div class="form-group">
                            <label class="col-md-5 text-right">Количество присваиваемых кодов</label>
                            <div class="col-md-6"><input type="number" name="col" min="1" value="{{old('col', 1)}}" class="form-control"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2"></div>
                            <div class="col-md-10 text-left">
                                <button type="submit" name="type" value="approve" class="btn btn-success btn-lg" role="button" aria-pressed="true">Утвердить</button>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('reason') ? ' has-error' : '' }}">
                            <div class="col-md-2"></div>
                            <div class="col-md-10 text-left">
                                <input type="text" name="reason" placeholder="Причина отклонения" class="form-control">
                                @if ($errors->has('reason'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('reason') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-2"></div>
                            <div class="col-md-10 text-left">
                                <button type="submit" name="type" value="decline" class="btn btn-danger btn-lg" role="button" aria-pressed="true">Отклонить</button>
                            </div>
                        </div>
                    </form>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
@if ($check)
@push('modals')
<div id="PhotoCheck" class="modal">
    <span class="close" data-dismiss="modal">&times;</span>

    <!-- Modal Content (The Image) -->
    <img class="modal-content" id="img01" src="{{$check->photo}}">

</div>
@endpush
@endif

resources/views/admin/export.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Export</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('check.export', Request::only('deleted')) }}">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="created_at_to" class="col-md-4 control-label">Название файла</label>

                            <div class='col-md-6 input-group'>
                                <input type='text' class="form-control input" name="name" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="created_at_from" class="col-md-4 control-label">Дата от</label>

                            <div class='col-md-6 input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="created_at_from" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="created_at_to" class="col-md-4 control-label">Дата до</label>

                            <div class='col-md-6 input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" name="created_at_to" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Export
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/export_files.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    &nbsp;
                    <li>
                        <a href="{{ route('check.export', Request::except('page')) }}">
                            Выгрузить
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li class="nav-item nav-link{{(!Request::get('deleted')) ? ' open' : ''}}">
                        <a href="{{route('check.list', Request::except('deleted'))}}" class="nav-link">Активные чеки</a>
                    </li>
                    <li class="nav-item nav-link{{(Request::get('deleted')) ? ' open' : ''}}">
                        <a href="{{route('check.list', array_merge(Request::all(), ['deleted' => 'y']))}}" class="nav-link">Отклоненные чеки</a>
                    </li>
                    <li class="nav-item nav-link">
                        <a href="{{route('check.export.files')}}" class="nav-link">Выгруженные чеки</a>
                    </li>
                </ul>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>

                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Действия</th>
                            </tr>
                        </thead>
                        @if ($files)
                        @foreach ($files as $file)
                        <tbody>
                        <tr>
                        <th scope="row">{{pathinfo($file)['filename']}}</th>
                        <td>
                            <form method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="file" value="{{pathinfo($file)['basename']}}">
                                <input type="submit" name="tyep" value="Download">
                            </form>
                        </td>
                        </tr>
                        @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/list.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    &nbsp;
                    <li>
                        <a href="{{ route('check.export', Request::except('page')) }}">
                            Выгрузить
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li class="nav-item nav-link{{(!Request::get('deleted')) ? ' open' : ''}}">
                        <a href="{{route('check.list', Request::except('deleted'))}}" class="nav-link">Активные чеки</a>
                    </li>
                    <li class="nav-item nav-link{{(Request::get('deleted')) ? ' open' : ''}}">
                        <a href="{{route('check.list', array_merge(Request::all(), ['deleted' => 'y']))}}" class="nav-link">Отклоненные чеки</a>
                    </li>
                </ul>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>

                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">УНП продавца</th>
                                <th scope="col">Дата</th>
                                <th scope="col">Серийный номер</th>
                                <th scope="col">Фото</th>
                                <th scope="col">Дата добавления</th>
                            </tr>
                        </thead>
                        @if ($checks)
                        @foreach ($checks as $check)
                        <tbody>
                        <tr>
                        <th scope="row">{{$check->id}}</th>
                        <td>{{$check->unp}}</td>
                        <td>{{$check->buy_time}}</td>
                        <td>{{$check->serial}}</td>
                        @if ($check->image)
                        <td><img src="{{$check->photo}}" class="img-thumbnail" style="max-width:80px;"></td>
                        @else
                        <td><a href="{{route('admin.view.check', ['check' => $check])}}" target="_blank">PDF</a></td>
                        @endif                        
                        <td>
                            {{$check->created_at}}
                            @if ($check->trashed() && $check->reason)
                            <br/>Причина: {{$check->reason}}
                            @endif
                        </td>
                        </tr>
                        @endforeach
                        @endif
                        </tbody>
                    </table>
                </div>

            </div>
            {{$checks->appends(Request::input())->links()}}
        </div>
    </div>
</div>
@endsection

resources/views/admin/sendsms.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Export</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('sendsms') }}">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="created_at_to" class="col-md-4 control-label">ID</label>

                            <div class='col-md-6 input-group'>
                                <input type='text' class="form-control input" name="id" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="created_at_to" class="col-md-4 control-label">Количество</label>

                            <div class='col-md-6 input-group'>
                                <input type='text' class="form-control input" name="count" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Send sms
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection